### ISSUE TITLE
Up/Down nav broken in text edit box

### ISSUE THREAD

**Issue by CBrophy** [evolvingstuff/MetaList#1] opened 2019-04-10 21:19 UTC
Firefox - fedora 29 x86_64

When editing a text item, pressing the up/down arrows to change lines seems to do nothing. It will also jump to the top or bottom of the text, or to the next page element.

**Comment by evolvingstuff** [comment] 2019-04-20 15:22
> When editing a text item, pressing the up/down arrows to change lines seems to do nothing

has been fixed in commit c77c86c

> It will also jump to the top or bottom of the text, or to the next page element

is by design, in order to navigate between subitems quickly. It will hopefully feel more intuitive now that previously mentioned bug has been fixed.

**Closed by evolvingstuff** 2019-04-20 15:22 UTC
